---
name: Deploy Blog

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy via SSH to tradefloor
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: 2222
                  script: |
                      cd ~/blog7x || git clone http://192.168.1.246:3000/undersleep7x/blog7x.git ~/blog7x
                      cd ~/blog7x
                      git pull
                      docker compose down
                      docker compose up -d --build
